name: cloudbase_dart
description: Dart plugin for cloudbase.
version: 0.0.3
homepage: https://www.cloudbase.net/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  dio: ^3.0.7
  crypto: ^2.1.3
  intl: ^0.16.1

dev_dependencies:
  test: ^1.14.7