name: cloudbase_core
description: Flutter plugin for cloudbase core.
version: 0.0.10
homepage: https://github.com/TencentCloudBase

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.7
  shared_preferences: ^0.5.6
  package_info: ^0.4.0+17
  crypto: ^2.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
