name: cloudbase_core
description: Flutter plugin for cloudbase core.
version: 0.0.4
homepage: https://github.com/TencentCloudBase

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.7
  shared_preferences: ^0.5.6
dev_dependencies:
  flutter_test:
    sdk: flutter
